---
title: "EDS 221 Day 2 Interactive Session"
author: "Kat Le"
format: html
execute: 
    warning: false
---

## Making & indexing data in R

### Vectors

Making vectors

```{r}
dogs <- c("teddy", "khora", "waffle", "banjo", "tallie")

# check class of dogs
typeof(dogs)
class(dogs)
str(dogs)
```

```{r}
my_breakfast <- c("waffles", 2, TRUE, "coffee")
typeof(my_breakfast)
```

```{r}
weights <- c(50, 60, 25, 35, 55)
typeof(weights)
class(weights)
```

```{r}
weights_integer <- c(50L, 60L, 25L, 35L, 55L)
typeof(weights_integer)
class(weights_integer)
```

```{r}
# is._() will ask if it is a certain class
is.numeric(weights_integer)
```

```{r}
zipcodes <- c(93105, 93514, 93101, 93401)

class(zipcodes)

# to change to a string, we'll us as._()
zipcodes_chr <- as.character(zipcodes)

class(zipcodes_chr)
```

### Create a vector with named elements

```{r}
dog_food <- c(teddy = "purina", khora = "alpo", waffle = "fancy feast", banjo = "blue diamond", tallie = "farmer's dog")
class(dog_food)

test <- c(cat = 4, dog = 10, elephant = 11)
class(test)
```

```{r}
# R uses a 1-index, first element of a vector gives a positional value of 1
# Python and Javascript uses 0-indexing, first element of a vector is 0
dog_food[2]
```

### Access ranges of values in a vector

Use : to refer to a range (low : high)

```{r}
trees <- c("ponderosa", "lodgepole", "jeffrey", "sugar", "white", "bristlecone")

trees[3]

trees[3:5]
```

## Warm-up for for loops

```{r}
i <- 3
trees[i]
```

```{r}
i <- seq(1:3) # seq(from = 1, to = 3)
trees[i]

```

```{r}
trees[3] <- "OAK"

trees
```
